/* Generated by Yosys 0.33+6 (git sha1 05f0262d775, gcc 13.2.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -Os) */

module mkPes_Sort(CLK, RST_N);
  input CLK;
  wire CLK;
  input RST_N;
  wire RST_N;
  wire [31:0] \sorter$put_x ;
  wire [31:0] v__h194;
  assign \sorter$put_x  = 32'h000000xx;
  assign v__h194 = 32'h000000xx;
endmodule
